version: '3'
services:
  app:
    container_name: geolingo-api
    restart: always
    build: .
    ports:
      - '8080:8080'
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    environment: 
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: geolingo
    security_opt:
      - seccomp:unconfined
    ports:
      - '3306:3306'